// GENERATED by tools/gen_account_flags.py from the vendored IDLs. Do not edit.
//
// Every flag here comes from the IDL the program was compiled against, not
// from Pump's prose tables -- which disagree with it on `fee_recipient`,
// `buyback_fee_recipient` and `global_volume_accumulator`, and produce
// transactions that fail without pointing at why.
//
// The one-based indices below are the positions that carry each flag, in
// account order. A test regenerates this file and fails if it has drifted, so
// a hand edit cannot reach a transaction.

/// `pump::buy_v2` -- 27 accounts.
pub const BUY_V2_ACCOUNT_COUNT: usize = 27;
pub const BUY_V2_WRITABLE: [usize; 14] = [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 22];
pub const BUY_V2_SIGNERS: [usize; 1] = [14];
pub const BUY_V2_NAMES: [&str; 27] = [
    "global",
    "base_mint",
    "quote_mint",
    "base_token_program",
    "quote_token_program",
    "associated_token_program",
    "fee_recipient",
    "associated_quote_fee_recipient",
    "buyback_fee_recipient",
    "associated_quote_buyback_fee_recipient",
    "bonding_curve",
    "associated_base_bonding_curve",
    "associated_quote_bonding_curve",
    "user",
    "associated_base_user",
    "associated_quote_user",
    "creator_vault",
    "associated_creator_vault",
    "sharing_config",
    "global_volume_accumulator",
    "user_volume_accumulator",
    "associated_user_volume_accumulator",
    "fee_config",
    "fee_program",
    "system_program",
    "event_authority",
    "program",
];

/// `pump::sell_v2` -- 26 accounts.
pub const SELL_V2_ACCOUNT_COUNT: usize = 26;
pub const SELL_V2_WRITABLE: [usize; 14] = [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21];
pub const SELL_V2_SIGNERS: [usize; 1] = [14];
pub const SELL_V2_NAMES: [&str; 26] = [
    "global",
    "base_mint",
    "quote_mint",
    "base_token_program",
    "quote_token_program",
    "associated_token_program",
    "fee_recipient",
    "associated_quote_fee_recipient",
    "buyback_fee_recipient",
    "associated_quote_buyback_fee_recipient",
    "bonding_curve",
    "associated_base_bonding_curve",
    "associated_quote_bonding_curve",
    "user",
    "associated_base_user",
    "associated_quote_user",
    "creator_vault",
    "associated_creator_vault",
    "sharing_config",
    "user_volume_accumulator",
    "associated_user_volume_accumulator",
    "fee_config",
    "fee_program",
    "system_program",
    "event_authority",
    "program",
];

/// `pump_amm::buy` -- 23 accounts.
pub const PUMPSWAP_BUY_ACCOUNT_COUNT: usize = 23;
pub const PUMPSWAP_BUY_WRITABLE: [usize; 9] = [1, 2, 6, 7, 8, 9, 11, 18, 21];
pub const PUMPSWAP_BUY_SIGNERS: [usize; 1] = [2];
pub const PUMPSWAP_BUY_NAMES: [&str; 23] = [
    "pool",
    "user",
    "global_config",
    "base_mint",
    "quote_mint",
    "user_base_token_account",
    "user_quote_token_account",
    "pool_base_token_account",
    "pool_quote_token_account",
    "protocol_fee_recipient",
    "protocol_fee_recipient_token_account",
    "base_token_program",
    "quote_token_program",
    "system_program",
    "associated_token_program",
    "event_authority",
    "program",
    "coin_creator_vault_ata",
    "coin_creator_vault_authority",
    "global_volume_accumulator",
    "user_volume_accumulator",
    "fee_config",
    "fee_program",
];

/// `pump_amm::sell` -- 21 accounts.
pub const PUMPSWAP_SELL_ACCOUNT_COUNT: usize = 21;
pub const PUMPSWAP_SELL_WRITABLE: [usize; 8] = [1, 2, 6, 7, 8, 9, 11, 18];
pub const PUMPSWAP_SELL_SIGNERS: [usize; 1] = [2];
pub const PUMPSWAP_SELL_NAMES: [&str; 21] = [
    "pool",
    "user",
    "global_config",
    "base_mint",
    "quote_mint",
    "user_base_token_account",
    "user_quote_token_account",
    "pool_base_token_account",
    "pool_quote_token_account",
    "protocol_fee_recipient",
    "protocol_fee_recipient_token_account",
    "base_token_program",
    "quote_token_program",
    "system_program",
    "associated_token_program",
    "event_authority",
    "program",
    "coin_creator_vault_ata",
    "coin_creator_vault_authority",
    "fee_config",
    "fee_program",
];
