"""Emit the Rust account-flag tables from the vendored IDLs.

The Rust builder carried three wrong flags for as long as it existed, because
they were transcribed from Pump's prose tables and the prose disagrees with the
program. Fixing them by hand fixes them once; generating them fixes them
permanently, and makes the next upstream change a regeneration rather than a
re-reading.

The Python route builds its account lists from the IDL at runtime. Rust cannot
without pulling in a JSON parser on the hot path, so the flags are baked in at
generation time instead, and a test asserts the checked-in file still matches
what this script produces. A hand edit that drifts from the IDL fails that
test rather than reaching a transaction.

    python tools/gen_account_flags.py            # write the file
    python tools/gen_account_flags.py --check    # exit 1 if it is stale
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Tuple

ROOT = Path(__file__).resolve().parents[1]
IDL_DIR = ROOT / "idl"
TARGET = ROOT / "native" / "solana_fastpath" / "src" / "generated_flags.rs"

# (rust prefix, idl file, instruction)
INSTRUCTIONS: Tuple[Tuple[str, str, str], ...] = (
    ("BUY_V2", "pump", "buy_v2"),
    ("SELL_V2", "pump", "sell_v2"),
    ("PUMPSWAP_BUY", "pump_amm", "buy"),
    ("PUMPSWAP_SELL", "pump_amm", "sell"),
)

HEADER = """// GENERATED by tools/gen_account_flags.py from the vendored IDLs. Do not edit.
//
// Every flag here comes from the IDL the program was compiled against, not
// from Pump's prose tables -- which disagree with it on `fee_recipient`,
// `buyback_fee_recipient` and `global_volume_accumulator`, and produce
// transactions that fail without pointing at why.
//
// The one-based indices below are the positions that carry each flag, in
// account order. A test regenerates this file and fails if it has drifted, so
// a hand edit cannot reach a transaction.

"""


def _flags(idl: Dict[str, Any], name: str) -> Tuple[List[int], List[int], List[str]]:
    entry = next(item for item in idl["instructions"] if item["name"] == name)
    accounts = entry["accounts"]
    writable = [index for index, account in enumerate(accounts, 1)
                if account.get("writable")]
    signer = [index for index, account in enumerate(accounts, 1)
              if account.get("signer")]
    return writable, signer, [account["name"] for account in accounts]


def render() -> str:
    parts = [HEADER]
    for prefix, idl_name, instruction in INSTRUCTIONS:
        idl = json.loads((IDL_DIR / f"{idl_name}.json").read_text(encoding="utf-8"))
        writable, signer, names = _flags(idl, instruction)
        parts.append(f"/// `{idl_name}::{instruction}` -- {len(names)} accounts.\n")
        parts.append(f"pub const {prefix}_ACCOUNT_COUNT: usize = {len(names)};\n")
        parts.append(
            f"pub const {prefix}_WRITABLE: [usize; {len(writable)}] = "
            f"{json.dumps(writable).replace('[', '[').replace(']', ']')};\n")
        parts.append(
            f"pub const {prefix}_SIGNERS: [usize; {len(signer)}] = "
            f"{json.dumps(signer)};\n")
        parts.append(
            f"pub const {prefix}_NAMES: [&str; {len(names)}] = [\n"
            + "".join(f'    "{name}",\n' for name in names) + "];\n\n")
    # rustfmt removes trailing blank lines. Emit its canonical EOF so running
    # the formatter cannot make a generated file immediately fail --check.
    return "".join(parts).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the checked-in file is stale")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != rendered:
            print(f"{TARGET} is stale; run python tools/gen_account_flags.py",
                  file=sys.stderr)
            return 1
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(rendered, encoding="utf-8")
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
